name: Test GitHub Actions
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: which docker

      - name: docker ps
        run: docker ps

      - name: ls
        run: ls -AlR

      - name: docker build
        run: docker build --tag testaction `pwd`/.github/actions/example

      - name: docker run
        run: docker run testaction
